### ISSUE TITLE
Individuals that cannot be displayed in trees.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#135]
Some individuals' perspective are unavailable and the tree is not generated / shown.
Other individuals in the same tree work correctly.

Reproduce:
1. In ftrees, search for First name Max last name Van Dam.
2. Click the Max Van Dam who is the son of Joanna and Aron. Everything should work fine.
3. Go back to search results and select the Max Van Dam son of Helena and Nn.
Result:
No tree loaded, both individuals belong to tree #9000

Console:
```
jquery.min.js:3 GET data:image/jpeg;base64,{{item.thumbnail}} net::ERR_INVALID_URL(anonymous function) @ jquery.min.js:3n.access @ jquery.min.js:2html @ jquery.min.js:3(anonymous function) @ angular.js:8434(anonymous function) @ angular.js:14634$eval @ angular.js:15878$digest @ angular.js:15689$apply @ angular.js:15986(anonymous function) @ angular.js:1658e @ angular.js:4473d @ angular.js:1656yc @ angular.js:1676Zd @ angular.js:1570(anonymous function) @ angular.js:28683j @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2I @ jquery.min.js:2
angular.js:12416 TypeError: Cannot read property 'id' of undefined
    at http://dbs.bh.org.il/js/bhsclient-1467197495832.min.js:2:27633
    at Array.forEach (native)
    at http://dbs.bh.org.il/js/bhsclient-1467197495832.min.js:2:27567
    at Array.forEach (native)
    at Object.render (http://dbs.bh.org.il/js/bhsclient-1467197495832.min.js:2:27031)
    at http://dbs.bh.org.il/js/bhsclient-1467197495832.min.js:2:25792
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:86:515
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:118:217
    at m.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:132:358)
    at m.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:129:365)
```

**Comment by daonb** [comment]
try http://test.dbs.bh.org.il/person/9000/I296 to get the error
